### ISSUE TITLE
Old Flag Has Resurfaced on Activity Stream

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/BP-Moderation#10]
After the most recent update, the old flag has resurfaced on the activity stream of the main site. It's fine on subsites.

![flag](https://cloud.githubusercontent.com/assets/480667/8640578/770166d2-28cb-11e5-9b17-0e48b62b53f5.png)

**Comment by r-a-y** [comment]
I couldn't duplicate this locally, but the issue could stem from having an older version of the CSS stylesheet.

I've added a commit that should bust the CSS cache.  Let me know if that fixes things for you.
