### ISSUE TITLE
Notification for Flag

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/BP-Moderation#2]
Many of our users don't use email, but they all see the Notifications from BuddyPress. Could a flag trigger a notification as well, or instead of, an email.

**Comment by r-a-y** [comment]
I can look into this.  What are the most pertinent notifications to add support for?

**Comment by mrjarbenne** [comment]
Activity Stream Post flags
Activity Stream Comment flags
Blog Post flags
Blog Comment flags
enhancement (later) bbPress Forum Posts (the plugin doesn't currently support bbPress)

Currently an email is sent whenever these items are flagged. A notification as well would be helpful for our younger users who don't regularly check email. I'm not sure how much content we can slide into a notification so I'll try to tighten up the notification. 

%content type% you posted has been flagged inappropriate

Brajesh has created something similar for blog comments: http://buddydev.com/plugins/bp-notify-post-author-blog-comment/

**Comment by r-a-y** [comment]
I'm starting work on this now.

Should a screen notification be sent regardless of the warning threshold option in the BP Moderation admin area?

Or should a screen notification only be sent when the warning threshold is reached?  Currently, in BP Moderation, when the warning threshold is reached, this is when an email is sent.

**Comment by mrjarbenne** [comment]
Let's respect the threshold here as well. I currently have it set to 1, which triggers every time, but it would be good to the capacity to dial it back if necessary.

**Comment by r-a-y** [comment]
Let me know what you think of the following workflow:

Let's say a user gets the notification - `One of your blog posts was marked as inappropriate` - and clicks on it.  I currently have this link to the blog post in question and then mark the notification as read.  Thinking from the user's perspective, if I click on this link and get redirected to the blog post, there isn't really any action to take.

Likewise, if a user has more than one blog post moderated, they'll get this notification - `X of your blog posts were flagged as inappropriate`.  If the user clicks on this, I have it so this takes you to the user's notifications page and marks all moderated blog post notifications as read.  When you're on the notifications page, you can still click on each individual notification and this will take you to the blog post.

I haven't pushed this code yet; just want some feedback before I proceed.

**Comment by mrjarbenne** [comment]
That sounds awesome.

**Comment by r-a-y** [comment]
Current master branch adds notifications support for the majority of content types except members, private message senders and plugins adding their own BP Moderation support.

At the moment, only blog posts have complete support.  By "complete support" I mean marking the notification as read as soon as you click on the notification's URL.

The rest will add a notification, but you'll manually have to mark the notification as read on your Notifications page.  I'll add "mark as unread" functionality to the other content types soon, but give master branch a twirl in a testing environment and let me know what you think.  (Also encountered a BP notifications cache bug in the process that I've added a patch for!)

**Comment by mrjarbenne** [comment]
As an author on a subdomain blog, I get this error in the dashboard when a comment has been marked as spam.

Fatal error: Class 'bpModeration' not found in /srv/www/wpmu-subdomain/wp-content/plugins/BP-Moderation/classes/bpModNotification.php on line 43

Clicking the notification that the comment has been flagged, takes you to the comment, but doesn't clear the notification.

**Comment by r-a-y** [comment]
> As an author on a subdomain blog, I get this error in the dashboard when a comment has been marked as spam.

I can't duplicate this.  Can you record a video demonstrating this?  Is BP Moderation network-activated?

> Clicking the notification that the comment has been flagged, takes you to the comment, but doesn't clear the notification.

Right, I haven't added "mark as read" support for anything other than blog posts at the moment.

**Comment by mrjarbenne** [comment]
http://www.screencast.com/t/WXG7ED1MqGB8

Sorry about the second piece. I thought the blog side was clearing notifications.

**Comment by r-a-y** [comment]
Thanks for the video!

I was testing with super admin access, which was why I didn't duplicate the error.  Should be fixed as of commit 9cfc522.

**Comment by mrjarbenne** [comment]
Cool. I'll test it out. Everything else so far seems to be working without issue.

**Comment by r-a-y** [comment]
I might make the mark notifications thing an automated process for all content types instead of having the specific content type needing its own mark notifications routine.

We'll lose a bit of specificity, but it might be worthwhile to do this.  Will look into it.

**Comment by mrjarbenne** [comment]
I would think that as soon as they click on it, we can safely mark it as read. They would still have a record of it in their notifications if they had not dealt with it immediately.

**Comment by r-a-y** [comment]
BP Moderation notifications should now be marked as read as soon as the user clicks on the notification link.

Give it a test with a variety of BP Moderation content types and let me know if it works as expected.

**Comment by mrjarbenne** [comment]
Working as expected.
