### ISSUE TITLE
Notify Blog Admin on Subdomain Comment Flag

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/BP-Moderation#4]
When content is flagged on a subdomain, would it be possible to also notify the blog admin. This would apply to user content from those with author or contributor capabilities, and to comments left on the blog. 

The SuperAdmin/Moderator email list in the Settings panel should still be notified as they are now: an administrator whose content is flagged isn't in a position to moderate their own content, particularly when the students are admin on their own blog.

**Comment by r-a-y** [comment]
Are we only talking about blog posts, comments and pages here?

**Comment by r-a-y** [comment]
Are we only talking about blog posts, comments and pages here?

**Comment by r-a-y** [comment]
Are we only talking about blog posts, comments and pages here?

**Comment by mrjarbenne** [comment]
Yes, Yes, Yes.

**Comment by r-a-y** [comment]
Ugh, sorry for the duplicate posts :)

**Comment by r-a-y** [comment]
One more Q, by "notify the blog admin", do you mean by email or by screen notification or both?

**Comment by mrjarbenne** [comment]
Email works. Is that easiest?

**Comment by r-a-y** [comment]
I've done email for now.

Here's a copy of the email content:

> Hi,
> 
> A blog [TYPE] was just flagged on your site.
> 
> You can view the flagged item here:
> [LINK]
> 
> The blog [TYPE] was reported by the user, [USER]:
> [USER LINK]

Let me know if you'd like to make any changes to it.

**Comment by mrjarbenne** [comment]
That's awesome
