### ISSUE TITLE
Button Array to Access Commons Functions

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/BP-Moderation#5]
Would an array of buttons that appeared to logged in users provide a more standardized means of accessing buttons like the Flag Inappropriate? 

Is there logic in adding to that array so that after I read a blog post, I can Follow that blog. Would that help to promote the use of that functionality?

In the new Favorites modality being examined in BP 2.4, is there room to hook into that functionality in multisite to be able to favorite blogs from the actual post on the subdomain, rather than on the excerpt created on the activity stream?

Each of these is its own ticket, if it's something we want to address. Here's what something like that might look like: 

![2015-06-04_14-38-18](https://cloud.githubusercontent.com/assets/480667/7991856/48d8b1b8-0ac9-11e5-8a5b-b1c74e169d7b.png)

**Comment by r-a-y** [comment]
Responded in another thread.

Closing this as the implementation above is not related to the BP Moderation plugin.
