### ISSUE TITLE
Unflag Text not Updating when Settings are Updated

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/BP-Moderation#6]
In the Settings menu in the dashboard, users are able to indicate what they would like the flag text to be. On the Activity feed, changes in the dashboard are reflected automatically on the button. The link in the post text doesn't reflect this change. Noting this here, with an awareness that over here we are working on a different method of displaying this button on blog posts: https://github.com/hwdsbcommons/HWDSB-Commons/issues/52

See video for further details.

http://www.screencast.com/t/OjjMf0KhJ

**Comment by r-a-y** [comment]
Regarding the button array for the Commons, I'm probably going to have to roll with custom code, but I've added a commit for this issue anyway.
