### ISSUE TITLE
Flag Content appearing in Post

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/BP-Moderation#8]
This was mentioned in #1, but that issue convo went off the rails. It's not consistently occuring, but is happening in this theme: https://wordpress.org/themes/blogsonry/ and in this theme https://wordpress.org/themes/ascetica/ as two examples. Previously I couldn't reproduce it because the theme I had seen it on had updated and rectified the issue. Here it is now in a manner that you might be able to investigate. Our button array will obviously attend to this. Just highlighting it here in case it is indicative of another issue: 

![2015-06-16_12-21-48](https://cloud.githubusercontent.com/assets/480667/8188203/64f2539c-1422-11e5-9c1b-e02772de0665.png)

**Comment by r-a-y** [comment]
Problem was only occurring when `the_excerpt()` was being used.  This happens on archive pages in some themes like the ones mentioned above.

Should be fixed as of commit 731b43c.

**Comment by mrjarbenne** [comment]
Thanks.

**Comment by mrjarbenne** [comment]
This is now fixed on an archive page, but not yet fixed on the main blog loop in cases where excerpts are used in the main feed.

**Comment by mrjarbenne** [comment]
Example: http://courses.commons.hwdsb.on.ca/

Note: I'm hiding the actual flag on this site with CSS.

**Comment by r-a-y** [comment]
Thanks for the report.  Fix should be live on production.

**Comment by mrjarbenne** [comment]
Looks like you got it. That was a weird one. Couldn't get it to appear consistently.
