### ISSUE TITLE
Dashboard Contents Record Doesn't Match Email Notifications

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/BP-Moderation#9]
The list of flagged content in the Network Dashboard isn't matching the number of emails I'm receiving when things are flagged. 

See video for details: http://www.screencast.com/t/jiZ3l90EfM

**Comment by r-a-y** [comment]
What could be causing the difference is that the reporter unflagged the content.  When a reporter unflags the content, the moderation record is deleted.

So what you're seeing in the dashboard is the accurate number, but the admin notification email goes out as soon as an item is flagged.

What I could do is to send an email whenever an item is unflagged as well, but that will increase the number of emails that an admin receives.

**Comment by mrjarbenne** [comment]
That makes good sense. I wasn't aware of that workflow. Don't send another email. It's already plenty.
